# [Introduction to Deep Learning with Keras](https://heartbeat.fritz.ai/introduction-to-deep-learning-with-keras-c7c3d14e1527)
Training an artificial neural network involves the following steps:

1. Weights are randomly initialized to numbers that are near zero but not zero.
2. Feed the observations of your dataset to the input layer.
3. Forward propagation (from left to right): neurons are activated and the predicted values are obtained.
4. Compare predicted results to actual values and measure the error.
5. Backward propagation (from right to left): weights are adjusted.
6. Repeat steps 1â€“5
7. One epoch is achieved when the whole training set has gone through the neural network.

## Business problem data

In [24]:
import pandas as pd
import numpy as np

df = pd.read_csv("data/insurance_claims.csv")

df

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,witnesses,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported
0,328,48,521585,2014-10-17,OH,250/500,1000,1406.91,0,466132,...,2,YES,71610,6510,13020,52080,Saab,92x,2004,Y
1,228,42,342868,2006-06-27,IN,250/500,2000,1197.22,5000000,468176,...,0,?,5070,780,780,3510,Mercedes,E400,2007,Y
2,134,29,687698,2000-09-06,OH,100/300,2000,1413.14,5000000,430632,...,3,NO,34650,7700,3850,23100,Dodge,RAM,2007,N
3,256,41,227811,1990-05-25,IL,250/500,2000,1415.74,6000000,608117,...,2,NO,63400,6340,6340,50720,Chevrolet,Tahoe,2014,Y
4,228,44,367455,2014-06-06,IL,500/1000,1000,1583.91,6000000,610706,...,1,NO,6500,1300,650,4550,Accura,RSX,2009,N
5,256,39,104594,2006-10-12,OH,250/500,1000,1351.10,0,478456,...,2,NO,64100,6410,6410,51280,Saab,95,2003,Y
6,137,34,413978,2000-06-04,IN,250/500,1000,1333.35,0,441716,...,0,?,78650,21450,7150,50050,Nissan,Pathfinder,2012,N
7,165,37,429027,1990-02-03,IL,100/300,1000,1137.03,0,603195,...,2,YES,51590,9380,9380,32830,Audi,A5,2015,N
8,27,33,485665,1997-02-05,IL,100/300,500,1442.99,0,601734,...,1,YES,27700,2770,2770,22160,Toyota,Camry,2012,N
9,212,42,636550,2011-07-25,IL,100/300,500,1315.68,0,600983,...,1,?,42300,4700,4700,32900,Saab,92x,1996,N
10,235,42,543610,2002-05-26,OH,100/300,500,1253.12,4000000,462283,...,2,?,87010,7910,15820,63280,Ford,F150,2002,N
11,447,61,214618,1999-05-29,OH,100/300,2000,1137.16,0,615561,...,2,YES,114920,17680,17680,79560,Audi,A3,2006,N
12,60,23,842643,1997-11-20,OH,500/1000,500,1215.36,3000000,432220,...,0,NO,56520,4710,9420,42390,Saab,95,2000,N
13,121,34,626808,2012-10-26,OH,100/300,1000,936.61,0,464652,...,1,NO,7280,1120,1120,5040,Toyota,Highlander,2010,N
14,180,38,644081,1998-12-28,OH,250/500,2000,1301.13,0,476685,...,2,YES,46200,4200,8400,33600,Dodge,Neon,2003,Y
15,473,58,892874,1992-10-19,IN,100/300,2000,1131.40,0,458733,...,0,NO,63120,10520,10520,42080,Accura,MDX,1999,Y
16,70,26,558938,2005-06-08,OH,500/1000,1000,1199.44,5000000,619884,...,2,YES,52110,5790,5790,40530,Nissan,Maxima,2012,N
17,140,31,275265,2004-11-15,IN,500/1000,500,708.64,6000000,470610,...,2,YES,77880,14160,7080,56640,Suburu,Legacy,2015,N
18,160,37,921202,2014-12-28,OH,500/1000,500,1374.22,0,472135,...,0,NO,72930,6630,13260,53040,Accura,TL,2015,N
19,196,39,143972,1992-08-02,IN,500/1000,2000,1475.73,0,477670,...,0,NO,60400,6040,6040,48320,Nissan,Pathfinder,2014,N
20,460,62,183430,2002-06-25,IN,250/500,1000,1187.96,4000000,618845,...,0,?,47160,0,5240,41920,Suburu,Impreza,2011,N
21,217,41,431876,2005-11-27,IL,500/1000,2000,875.15,0,442479,...,2,?,37840,0,4730,33110,Accura,RSX,1996,N
22,370,55,285496,1994-05-27,IL,100/300,2000,972.18,0,443920,...,0,YES,71520,17880,5960,47680,Suburu,Forrestor,2000,Y
23,413,55,115399,1991-02-08,IN,100/300,2000,1268.79,0,453148,...,2,?,98160,8180,16360,73620,Dodge,RAM,2011,Y
24,237,40,736882,1996-02-02,IN,100/300,1000,883.31,0,434733,...,3,NO,77880,7080,14160,56640,Ford,Escape,2005,N
25,8,35,699044,2013-12-05,OH,100/300,2000,1266.92,0,613982,...,3,YES,71500,16500,11000,44000,Ford,Escape,2006,Y
26,257,43,863236,1990-09-20,IN,100/300,2000,1322.10,0,436984,...,3,YES,9020,1640,820,6560,Toyota,Camry,2005,N
27,202,34,608513,2002-07-18,IN,100/300,500,848.07,3000000,607730,...,1,?,5720,1040,520,4160,Suburu,Forrestor,2003,Y
28,224,40,914088,1990-02-08,OH,100/300,2000,1291.70,0,609837,...,0,YES,69840,7760,15520,46560,Dodge,Neon,2009,N
29,241,45,596785,2014-03-04,IL,500/1000,2000,1104.50,0,432211,...,2,NO,91650,14100,14100,63450,Accura,TL,2011,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,213,35,844129,1990-09-20,OH,250/500,500,871.46,0,477938,...,0,YES,74140,13480,6740,53920,Ford,Escape,2007,N
971,79,25,732169,2000-11-05,OH,500/1000,500,1863.04,0,462698,...,1,?,67800,13560,6780,47460,Mercedes,C300,1995,N
972,232,44,221854,1994-10-03,OH,250/500,2000,1181.64,0,454552,...,1,YES,55400,5540,11080,38780,Jeep,Grand Cherokee,2002,Y
973,230,37,776950,2005-04-11,IL,500/1000,1000,1060.74,0,471585,...,3,?,49100,9820,4910,34370,Suburu,Impreza,1996,Y
974,234,41,291006,1990-05-16,IN,100/300,500,951.56,0,455426,...,1,?,98280,15120,7560,75600,Chevrolet,Tahoe,2007,Y
975,240,40,845751,2004-09-11,IN,100/300,500,1533.71,9000000,469856,...,2,?,66550,6050,12100,48400,Ford,Escape,2008,N
976,143,33,889764,1993-11-30,OH,500/1000,1000,1200.09,0,454191,...,2,?,70400,14080,7040,49280,Accura,RSX,2002,N
977,266,42,929306,2003-03-06,IN,100/300,500,1093.83,4000000,468454,...,1,NO,53280,4440,8880,39960,Suburu,Impreza,2015,Y
978,89,32,515457,1996-12-18,IN,250/500,1000,988.93,0,614187,...,3,YES,84590,15380,15380,53830,Dodge,Neon,1999,N
979,229,37,556270,1995-02-21,IN,500/1000,1000,1331.94,0,433974,...,2,YES,54560,9920,9920,34720,Saab,95,2004,N
980,245,40,908935,2009-12-11,IL,500/1000,1000,1361.45,0,604833,...,2,YES,82170,7470,7470,67230,Suburu,Forrestor,1999,N
981,50,44,525862,2000-10-18,OH,250/500,2000,1188.51,0,447469,...,2,NO,61100,6110,12220,42770,Dodge,Neon,2008,N
982,230,43,490514,2007-02-09,IN,500/1000,2000,1101.83,0,451529,...,3,YES,51900,5190,10380,36330,BMW,M5,2011,Y
983,17,39,774895,2006-10-28,IL,250/500,1000,840.95,0,431202,...,1,?,3440,430,430,2580,Suburu,Legacy,2002,N
984,163,36,974522,2000-01-27,IN,250/500,1000,1503.21,0,448190,...,1,NO,51390,5710,11420,34260,Toyota,Corolla,2013,N
985,29,32,669809,2002-04-05,OH,100/300,1000,1722.50,0,453713,...,2,?,76900,7690,7690,61520,Jeep,Wrangler,1995,N
986,232,42,182953,2013-04-30,IN,100/300,500,944.03,0,440153,...,3,?,77000,15400,7700,53900,Toyota,Highlander,2015,Y
987,235,39,836349,2013-05-01,IL,500/1000,2000,1453.61,4000000,619570,...,3,?,60320,9280,9280,41760,Chevrolet,Tahoe,2012,Y
988,295,46,591269,1999-01-09,IN,100/300,500,1672.88,0,478947,...,1,NO,60700,12140,6070,42490,Honda,Civic,1997,N
989,22,21,550127,2007-07-04,IN,250/500,1000,1248.05,0,443550,...,2,?,53280,5920,0,47360,Chevrolet,Malibu,2015,N
990,286,43,663190,1994-02-05,IL,100/300,500,1564.43,3000000,477644,...,2,YES,34290,3810,3810,26670,Jeep,Grand Cherokee,2013,N
991,257,44,109392,2006-07-12,OH,100/300,1000,1280.88,0,433981,...,1,NO,46980,0,5220,41760,Accura,TL,2002,N
992,94,26,215278,2007-10-24,IN,100/300,500,722.66,0,433696,...,2,YES,36700,3670,7340,25690,Nissan,Pathfinder,2010,N
993,124,28,674570,2001-12-08,OH,250/500,1000,1235.14,0,443567,...,1,?,60200,6020,6020,48160,Volkswagen,Passat,2012,N
994,141,30,681486,2007-03-24,IN,500/1000,1000,1347.04,0,430665,...,2,YES,6480,540,1080,4860,Honda,Civic,1996,N
995,3,38,941851,1991-07-16,OH,500/1000,1000,1310.80,0,431289,...,1,?,87200,17440,8720,61040,Honda,Accord,2006,N
996,285,41,186934,2014-01-05,IL,100/300,1000,1436.79,0,608177,...,3,?,108480,18080,18080,72320,Volkswagen,Passat,2015,N
997,130,34,918516,2003-02-17,OH,250/500,500,1383.49,3000000,442797,...,3,YES,67500,7500,7500,52500,Suburu,Impreza,1996,N
998,458,62,533940,2011-11-18,IL,500/1000,2000,1356.92,5000000,441714,...,1,YES,46980,5220,5220,36540,Audi,A5,1998,N
999,456,60,556080,1996-11-11,OH,250/500,1000,766.19,0,612260,...,3,?,5060,460,920,3680,Mercedes,E400,2007,N

# convert the categorical columns to dummy variables.

In [27]:
feats = ["policy_state",
         "insured_sex",
         "insured_education_level",
         "insured_occupation",
         "insured_hobbies",
         "insured_relationship",
         "collision_type",
         "incident_severity",
         "authorities_contacted",
         "incident_state",
         "incident_city",
         "incident_location",
         "property_damage",
         "police_report_available",
         "auto_make",
         "auto_model",
         'fraud_reported',
         "incident_type"]

df_final = pd.get_dummies(df,columns=feats,drop_first=True)

df_final.shape

(1000, 1147)

# split the data into a training set and a test set.

In [19]:
from sklearn.model_selection import train_test_split

X = df_final.drop(["fraud_reported_Y",
                   "policy_csl",
                   "policy_bind_date",
                   "incident_date"],axis=1).values

y = df_final["fraud_reported_Y"].values

In [23]:
y.shape

(1000,)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

## Scale the dataset

In [16]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
X_train.shape

(700, 1143)

## Building the Artificial Neural Network

In [15]:
import keras
from keras.models import Sequential
from keras.layers import Dense

classifier = Sequential()

classifier.add(
     Dense(3, kernel_initializer = "uniform",
              activation = "relu", input_dim=5))

classifier.add(
     Dense(3, kernel_initializer = "uniform",
              activation = "relu"))
classifier.add(
     Dense(1, kernel_initializer = "uniform",
              activation = "sigmoid"))

classifier.compile(optimizer= "adam",
                  loss = "binary_crossentropy",
                  metrics = ["accuracy"])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

y_pred = classifier.predict(X_test)

y_pred = (y_pred > 0.5)

y_pred

ValueError: Error when checking input: expected dense_13_input to have shape (5,) but got array with shape (1143,)

## Checking the confusion matrix

In [12]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

NameError: name 'y_pred' is not defined

In [ ]:
#new_pred = classifier.predict(sc.transform(np.array([[a,b,c,d]])))

from keras.wrappers.scikit_learn import KerasClassifier

from sklearn.model_selection import cross_val_score

def make_classifier():
    classifier = Sequential()
    classifier.add(Dense(3, kernel_initializer = "uniform", activation = "relu", input_dim=5))
    classifier.add(Dense(3, kernel_initializer = "uniform", activation = "relu"))
    classifier.add(Dense(1, kernel_initializer = "uniform", activation = "sigmoid"))
    classifier.compile(optimizer= "adam",loss = "binary_crossentropy",metrics = ["accuracy"])
    return classifier

accuracies = cross_val_score(estimator = classifier,
                             X = X_train,
                             y = y_train,
                             cv = 10,
                             n_jobs = -1)

mean = accuracies.mean()
variance = accuracies.var()

from keras.layers import Dropout

classifier = Sequential()
classifier.add(Dense(3, kernel_initializer = "uniform", activation = "relu", input_dim=5))

# Notice the dropouts
classifier.add(Dropout(rate = 0.1))
classiifier.add(Dense(6, kernel_initializer = "uniform", activation = "relu"))
classifier.add(Dropout(rate = 0.1))

classifier.add(Dense(1, kernel_initializer = "uniform", activation = "sigmoid"))
classifier.compile(optimizer= "adam",loss = "binary_crossentropy",metrics = ["accuracy"])

from sklearn.model_selection import GridSearchCV

def make_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(6, kernel_initializer = "uniform", activation = "relu", input_dim=11))
    classifier.add(Dense(6, kernel_initializer = "uniform", activation = "relu"))
    classifier.add(Dense(1, kernel_initializer = "uniform", activation = "sigmoid"))
    classifier.compile(optimizer= optimizer,loss = "binary_crossentropy",metrics = ["accuracy"])
    return classifier

classifier = KerasClassifier(build_fn = make_classifier)

params = {
    "batch_size":[20,35],

    "nb_epoch":[150,500],

    "Optimizer":['adam','rmsprop']
}

grid_search = GridSearchCV(estimator=classifier,
                           param_grid=params,
                           scoring="accuracy",
                           cv=10)

grid_search = grid_search.fit(X_train,y_train)

best_param = grid_search.best_params_

best_accuracy = grid_search.best_score_